FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt ./

RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt --no-cache-dir

# COPY backend/foodgram_backend/ ./
COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "foodgram_backend.wsgi"]